---
language: python
python:
    - "3.8"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio check
    - platformio run
